[package]
name = "battlesnake"
version = "0.1.0"
authors = ["q"]
edition = "2018"

[dependencies]
tiny_http = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
rand = "0.6.5"
indextree = "3.1.1"
time = "*"